name: Auto Release

on:
  push:
    branches:
      - main

permissions:
  contents: write   # IMPORTANT FIX

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Tag
        id: tag
        run: echo "TAG=v1.$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2   # UPDATED VERSION
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          name: Release ${{ steps.tag.outputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}